export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'; 